sudo: false

language: c

os:
    - linux

compiler:
    - gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.9
            - g++-4.9
            - autopoint
            - python-lxml
            - libgl1-mesa-dev

cache:
    directories:
        - cmake-2.8.12.2
        - llvm-fastcomp
        - protobuf

env:
    global:
        # GH_TOKEN scope=public_repo, for pushing to gh-pages demo site,
        # limited to builds of the rib/gputop repo
        - secure: "AuIFOUWwEZq+SoBqnH/9CjGtAI3t2lfBLwKrA04ZqyTJ4Z9F/I0hHP4msSZAdRrwrWDf97pwjEYN4Ll4+W5c2+N95Nks+jCZnRAvQi4uC7mlF+5dRBwSYcyz49t3kK6r986jowfxvqELZsl/8Q2ZQvrOnpAekuQ1oWjGmdXr1bfqDJyvahRKaB5zsIVkPAguSR5f2IFBkOhTaDo24i/LFFMPx9yR7p3/mhRke+yfq7xJlGzV7/wIKqB5ZgP+q3C3BKumBCgsEKIdvW/H/Ff8GzanREx9vs5EjEI9OA/Mtt/mkHLJDviqTkjhIkMaDC/5hHDYk/z2wQEBR2FE5FJqvtrdAyr/5GjUL5EzWWGzBN0r4WDVcbmzWQDCaMp3CHJbn8GG5pk5JKzeMVX5Yc/t37J0y3ESYNaaR/jFwEJB/7chYVftvL2afU6m6ySCZ6J7pX3TWVjd449QSFJyQ9LSawFhaKPvoNJ07upCTBS2PpzFcxvGhkF6xt3lNnwxKyQBpORVXlPQ9oNvrUBS2to+NiNm1sT0Ba6EQT592V+tXppnIE8vD6R0D1pcOZvwqnCm1UxmTpIqYWHojvAAG0V8LW0hbBdmrEEY5sj6BqFHP8MOSTp032Z/DJOCUqVwrO/2Md59RuWcMIlMmiCs7Dmq9Ht9OLxKaGHHI/3ep0mIvc0="
    matrix:
        - CONFIG_OPTS="--enable-debug --enable-gl --disable-webui"
        - CONFIG_OPTS="--disable-debug --enable-gl --disable-webui"
        - CONFIG_OPTS="--enable-debug --disable-gl --disable-webui"
        - CONFIG_OPTS="--disable-debug --disable-gl --disable-webui"
        - CONFIG_OPTS="--enable-debug --disable-gl --enable-webui"
        - CONFIG_OPTS="--disable-debug --disable-gl --enable-webui"

before_install:
    # We don't want to depend on a special version of gcc for building gputop but building
    # llvm-fastcomp depends on a more recent toolchain :-/
    - export CC=gcc-4.9 CXX=g++-4.9
    # Kind of annoying how awkward it is to get a recent version of cmake on Travis a.t.m :-/
    - (if test -f cmake-2.8.12.2/bin/cmake; then echo OK; else
           git clone --branch v2.8.12.2 --single-branch --depth 1 git://cmake.org/cmake.git cmake-2.8.12.2-src &&
           cd cmake-2.8.12.2-src &&
           ./configure --prefix=$TRAVIS_BUILD_DIR/cmake-2.8.12.2 &&
           make &&
           make install;
       fi)
    # Building llvm-fastcomp manually helps us minimize the size of the directory we cache between builds...
    - (if test -d llvm-fastcomp/bin; then echo OK; else
           git clone https://github.com/kripken/emscripten-fastcomp &&
           git clone https://github.com/kripken/emscripten-fastcomp-clang emscripten-fastcomp/tools/clang &&
           mkdir emscripten-fastcomp/build &&
           cd emscripten-fastcomp/build &&
           PATH="$TRAVIS_BUILD_DIR/cmake-2.8.12.2/bin:$PATH" LDFLAGS="-s" CFLAGS="-Os" CXXFLAGS="-Os" cmake .. -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/llvm-fastcomp -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD="X86;JSBackend" -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_TESTS=OFF -DCLANG_INCLUDE_TESTS=OFF &&
           make -j4 &&
           make install;
       fi)
    - export LLVM="$TRAVIS_BUILD_DIR/llvm-fastcomp/bin"
    - git clone --single-branch --branch master --depth 1 https://github.com/kripken/emscripten
    - export PATH="$TRAVIS_BUILD_DIR/emscripten:$PATH"
    - emcc -v
    # Try not to depend on a special version of gcc/clang for anything else...
    - export CC=gcc CXX=g++
    - (if test -d protobuf/lib; then echo OK; else
            git clone --single-branch --branch master --depth 1 https://github.com/google/protobuf protobuf-src &&
            cd protobuf-src &&
            ./autogen.sh &&
            ./configure --prefix=$TRAVIS_BUILD_DIR/protobuf &&
            make &&
            make install;
       fi)
    - export PKG_CONFIG_PATH="$TRAVIS_BUILD_DIR/protobuf/lib/pkgconfig"
    # Fetch glext.h header including INTEL_performance_query enums
    - $(mkdir GL && cd GL && wget https://raw.githubusercontent.com/rib/mesa/wip/rib/oa-next/include/GL/glext.h)
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3

before_script:
    - NOCONFIGURE=1 ./autogen.sh

script:
    - ./configure $CONFIG_OPTS --prefix=$TRAVIS_BUILD_DIR/install && make V=1 && make V=1 install
    - export GPUTOP_TRAVIS_MODE=1
    - cd $TRAVIS_BUILD_DIR/install/bin
    - ./gputop --fake ./gputop-system
    - if [ "${CONFIG_OPTS/'enable-webui'}" != "$CONFIG_OPTS" ]; then ./gputop --fake --remote ./gputop-system 2> travis_log& sleep 3; firefox http://localhost:7890& sleep 10; grep OpenQuery travis_log; cat travis_log; fi
    - cd -

deploy:
    provider: script
    script: ./scripts/deploy-demo-site.sh
    skip_cleanup: true
    on:
        condition: $CONFIG_OPTS = "--disable-debug --disable-gl --enable-webui"
        branch: master
